# -*- coding: utf-8 -*-
"""22-8-24(Part1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8_Q4wlH1dWuaH2NMIMDCpF6AkODOkbH
"""

#sum of digits of user input integer
def sum_of_digits(n):
    if n == 0:
        return 0
    else:
        return n % 10 + sum_of_digits(n // 10)

# Example usage:
user_input = int(input("Enter an integer: "))
result = sum_of_digits(user_input)
print(f"The sum of the digits is: {result}")

