# -*- coding: utf-8 -*-
"""22-8-24(Part 2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12K0jO1WJWcXw2Qg_lJ3U0eMmk7cYyizZ
"""

#Reverse of user entered integer
def reverse_number(n, rev=0):
    if n == 0:
        return rev
    else:
        rev = rev * 10 + n % 10
        return reverse_number(n // 10, rev)

# Example usage:
user_input = int(input("Enter an integer: "))
reversed_number = reverse_number(user_input)
print(f"The reversed number is: {reversed_number}")